[project]
name = "django-sql-profiling-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2rc1",
]

[dependency-groups]
dev = [
    "django-silk>=5.3.2",
    "ruff>=0.11.2",
]
